import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Libre_Bodoni, Caudex } from "next/font/google";

const libreBodoni = Libre_Bodoni({
  subsets: ["latin"],
  variable: "--font-libre-bodoni",
  weight: ["400", "500", "600", "700"],
});

const caudex = Caudex({
  subsets: ["latin"],
  variable: "--font-caudex",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Joalharia Cavalinho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libreBodoni.variable} ${caudex.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
